### PR TITLE
Massive cleanup

### PR DESCRIPTION
**Pull request by ghost**
Should make changes to the site in future easier.

### CODE REVIEW

**Comment by ghost** [comment]
Just FIY: this will drastically improve edits in the future. As TBR is a bit on a stand still now, I think reconsidering other services might be an idea as well. I would try to see what blogging using html gives. With some rules in the .htaccess file (to hide it from clients) you can easily create a template blog file, which just needs some text. Then create another php file to render maybe ten blog posts, and you're good to go. If wanted, comments can go with a thirdparty service. 

I will integrate status detection in future (if wanted).

**Comment by ghost** [comment]
schermafbeelding 2016-03-12 om 16 53 26

**Comment by ghost** [comment]
Any news about this?

**Comment by laurelmay** [comment]
Sorry, I thought feedback had already been provided on this pull request. Very sorry that you've been waiting so long to hear back.

Unfortunately, this change is not able to be accepted. It is crucial that our main site use only client-side technologies—nothing that requires some sort of script execution on the server. With the exception of JavaScript, we want the site to be entirely static.

We do greatly appreciate the work you put into this PR, as well as all the other work you've done. These changes simply don't fit with TBR's long team plans for our site, which is unfortunate. The code and style are definitely of wonderful quality, though.

**Comment by ghost** [comment]
Well, you can always use some of the code to improve the status page etc.

**Pull request closed without merging**
